### ISSUE TITLE
Automate website creation

### ISSUE THREAD

**Issue by combe15** [combe15/factorio-whiteboard#49]
Would like to find a way to use Github actions to auto-generate a useable static website from the content that is in the repo.

I would like images, titles, and descriptions to be shown when viewing the repo's website.

With how GitHub pages work, the end product must be a static website, so Jquery, PHP, or any other dynamic website maker, will not be useable.

**Comment by chi-feng** [comment]
I'll create a fork using material mkdocs static site builder. I also have a github actions workflow for publishing the site in the `gh-pages` branch, so you can enable GitHub Pages for that branch (I think it's the default config). 

I've had a good experience with it in the past since it has a very shallow learning curve to author content because all the documentation pages are in markdown and a single mkdocs.yaml file is all you need.
